sudo: required

services:
  - docker

language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

jdk:
  - oraclejdk8

script:
  - TAG_NAME=$(echo ${TRAVIS_BRANCH} | sed -e 's/\//_/g')
  - docker build . --tag "fredboat/fredboat:${TAG_NAME}"

#Purge the crowdin bagde from GitHub
after_script: curl -X PURGE https://camo.githubusercontent.com/c36bc6df50e906552d4c516441da2601ebb41d85/68747470733a2f2f64333232637174353834626f346f2e636c6f756466726f6e742e6e65742f66726564626f61742f6c6f63616c697a65642e737667

after_success:
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push fredboat/fredboat;

#script: mvn clean install sonar:sonar -Dsonar.host.url=http://192.210.193.136:9000/ -Dsonar.login=$SONAR_TOKEN
