# when running this in development you probably want to symlink/copy your config and credentials files
# from the FredBoat directory to project root

version: '3'
services:
  db:
    build: ./docker/database/
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
  bot:
    build: .
    volumes:
      - ./config.yaml:/opt/FredBoat/config.yaml
      - ./credentials.yaml:/opt/FredBoat/credentials.yaml
      - ./logs:/opt/FredBoat/logs
    ports:
      - 1356:1356
    depends_on:
      - db
