# when running this in development you probably want to symlink/copy your config and credentials files
# from the FredBoat directory to project root

version: '3'
services:
  db:
    build: ./docker/database/
    restart: always

    # if you are running under windows you need to comment out the following two lines:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    # if you are running under windows and want to take manual backups of the database
    # via a docker volume, uncomment the following two lines and read the snippet at the bottom of this file
    #volumes:
      #- postgres-data-volume:/var/lib/postgresql/data

  bot:
    build: .
    volumes:
      - ./config.yaml:/opt/FredBoat/config.yaml
      - ./credentials.yaml:/opt/FredBoat/credentials.yaml
      - ./logs:/opt/FredBoat/logs
    ports:
      - 1356:1356
    restart: on-failure:3
    depends_on:
      - db

# If you are running on Windows and want to be able to backup the postgres data volume, run
#
#   docker volume create --name postgres-data-volume -d local
#
# and uncomment the following lines:
#
#volumes:
#  postgres-data-volume:
#    external: true
