version: '3'
services:
  db:
    build: ./docker/database/
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
  bot:
    build: .
    volumes:
      - ./config.yaml:/opt/FredBoat/config.yaml
      - ./credentials.yaml:/opt/FredBoat/credentials.yaml
    ports:
      - 1356:1356
    depends_on:
      - db
