---
################################################################
###                    *** WARNING ***
################################################################
###
### ALMOST EVERYTHING REQUESTED IN THIS FILE ARE CONFIDENTIAL CREDENTIALS
### IF YOU POST THIS FILE ONLINE (such as on GitHub) YOUR BOT COULD BE COMPROMISED
###
###
### Use a proper text editor when editing this file, for example Sublime.
### Do not use tab characters in this file, use plain spaces.
###
### Keep at least one space after a colon, like so:
###
###   key: value
###
###
### You can wrap most values into quotation marks, except numbers and booleans:
###
###   someUrl: "http://example.com"
###   someToken: "123.qwe.456[DFG="
###   somePortNumber: 22
###   useSomeFeature: true
###
###
### You can have a list of things like this:
###
###   listOfStrings: ["string1", "string2", "string3"]
###
### or like this:
###
###   listOfStrings:
###     - "string1"
###     - "string2"
###     - "string3"
###
###
### More information on correctly formatting yaml files: http://www.yaml.org/start.html


################################################################
###                 Basic configuration
################################################################

config:
  development:       true         # Set this to false for selfhosting. If you leave this enabled and complain about weird
                                  # things happening to your bot in the selfhosting chat you will be publicly taunted.
  prefix:            '<<'         # Default prefix used by the bot
  restServerEnabled: false        # Set this to true to enable FredBoats legacy API. Might cause issues when running several bots together
  botAdmins:         []           # Add comma separated userIds and roleIds that should have access to bot admin commands. Find role ids with the ;;roleinfo command
  autoBlacklist:     true         # Set to true to automatically blacklist users who frequently hit the rate limits
  game:              ""           # Set the displayed game/status. Leave empty quote marks for the default status
  continuePlayback:  false        # Set to true to force the player to continue playback even if left alone

server:
  port: 1356                      # Change the port of the API FredBoat exposes
spring:
  main:
    web-application-type: reactive # Do not touch for now. This will enable / disable a possible future FredBoat API


audio-sources:
  enableYouTube:     true         # Set to true to enable playing YouTube links
  enableSoundCloud:  true         # Set to true to enable playing SoundCloud links
  enableBandCamp:    true         # Set to true to enable playing BandCamp links
  enableTwitch:      true         # Set to true to enable playing Twitch links
  enableVimeo:       true         # Set to true to enable playing Vimeo links
  enableMixer:       true         # Set to true to enable playing Mixer links
  enableSpotify:     true         # Set to true to enable playing Spotify links
  enableLocal:       false        # Set to true to enable playing local files
  enableHttp:        false        # Set to true to enable playing direct links


################################################################
###                 Essential credentials
################################################################
credentials:
  # Add your discord bot token below, between the quotation marks
  # Find the token of your bot on https://discordapp.com/developers/applications/me
  # Tutorial: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
  discordBotToken: "PutYourDiscordBotTokenHere"


  # Used by the ;;split and ;;np commands. Must be hooked up to the Youtube Data API.
  # You can add additional keys in case you are running a big bot
  # How to get the key: https://developers.google.com/youtube/registering_an_application
  # Add your google API key between the quotation marks
  googleApiKeys:
    - "PutYourGoogleAPIKeyHere"



################################################################
###                     Optional APIs
################################################################

  # For the ;;mal command
  # Create an account on https://myanimelist.net/ and enter its login below
  malUser:        ""
  malPassword:    ""


  # Used to access imgur galleries for some RandomImageCommands
  # Acquired from here: https://api.imgur.com/oauth2/addclient
  # Choose an option that does not require an Authorization callback URL
  imgurClientId:  ""


  # Used to retrieve Spotify playlists
  # Get them from here: https://developer.spotify.com/my-applications
  spotifyId:      ""
  spotifySecret:  ""


  # Used by ;;weather command.
  # Get them from: http://openweathermap.org/appid
  openWeatherKey: ""

  # Error aggregation service https://sentry.io/
  sentryDsn:      ""



event-logger:
  # Webhooks to Discord channels that will post some guild stats and shard status changes
  # More information on webhooks: https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  # Example: "https://canary.discordapp.com/api/webhooks/1234567890/QWERTZUIOPasdfghjklYXCVBNM" (no, this one will not work)
  eventLogWebhook:            "" # webhook url for connect / disconnect events
  eventLogInterval:           1  # interval at which connect / disconnect events are posted in minutes
  guildStatsWebhook:          "" # webhook url for guild stats
  guildStatsInterval:         60 # interval at which guild stats are posted in minutes



################################################################
###        Developers and very experienced users only
################################################################

database:
  main:
    # FredBoat was written to work with PostgreSQL.
    # If you are running with docker-compose then you don't need to change the jdbcUrl here.
    # In PostgreSQL, role means user and vice versa. Keep that in mind when reading the following help and the provided links.
    # If you are running your own PostgreSQL database, you will need to provide a role and a database belonging to that role.
    # The role needs at least the permission to log in.
    # All postgres databases used by FredBoat are required to have the Hstore extension enabled.
    # Learn more about roles here: https://www.postgresql.org/docs/10/static/database-roles.html
    # Learn more about creating databases here: https://www.postgresql.org/docs/10/static/manage-ag-createdb.html
    # Learn more about the postgres jdbc url here: https://jdbc.postgresql.org/documentation/head/connect.html
    # Learn more about creating extensions here: https://www.postgresql.org/docs/current/static/sql-createextension.html
    # If you are using an SSH tunnel, you need to point your jdbc url to localhost and the configured tunnelLocalPort
    # Example jdbc: "jdbc:postgresql://localhost:5432/fredboat?user=fredboat&password=youshallnotpass"
    jdbcUrl:          ""

    # Ssh tunnel for a remote database. this is useful for when you don't want to expose your database on the remote server
    # and instead use ssh tunneling to access it
    # If you are running with docker-compose then you don't need to change any ssh value here.
    # If you are using an SSH tunnel, you need to point your jdbc url to localhost and the configured tunnelLocalPort
    # Keep the sshHost an empty string for no tunnel.
    tunnel:
      host:           ""         # add the ssh port to the ip / url, usually 22, for example: "db.example.com:22"
      user:           ""         # user on the remote machine
      privateKeyFile: ""         # path to an ssh private key file which is authorized to log in to the sshUser on the remote machine. learn how to create these: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04#step-four-—-add-public-key-authentication-(recommended)
      keyPass:        ""         # optional passphrase for the ssh key file
      localPort:      5432       # endpoint port of the tunnel on the machine running fredboat; makes sure these dont collide; this one needs to be used in the jdbc url
      remotePort:     5432       # port of the PostgreSQL on the remote machine, 5432 by default

  cache:
    # Database for caching things, see config of main database above for details about the individual values.
    # If you are running with docker-compose then you don't need to change the cache jdbcUrl here.
    # The main and cache databases can be two databases inside a single postgres instance.
    # They CANNOT be the same database due to the way flyway migrations work.
    # The main benefit is that you don't have to backup/migrate the cache database, it can just be dropped/recreated
    # If you do not provide a jdbc url for the cache database, FredBoat will still work (most likely), but may have a degraded
    # performance, especially in high usage environments and when using Spotify playlists.
    # If you are going to use two different ssh tunnels for both database connections, make sure that the local tunnel ports don't collide
    jdbcUrl:          ""
    tunnel:
      host:           ""
      user:           ""
      privateKeyFile: ""
      keyPass:        ""
      localPort:      5433
      remotePort:     5432


# If you are running lavalink nodes this is the place to add them.
# Examples shown below, don't forget to uncomment them properly.
# More on Lavalink: https://github.com/Frederikam/Lavalink
#lavalink:
#  nodes:
#    - name : "local"
#      host : "ws://localhost:5555"
#      pass : "youshallnotpass"
#    - name : "remote1"
#      host : "ws://192.168.1.20:5556"
#      pass : "youshallnotpass"
#    - name : "remote2"
#      host : "ws://lavalink.example.com:5557"
#      pass : "youshallnotpass"
